plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: ${LINKER:-pnp}

httpProxy: ${http_proxy:-}
httpsProxy: ${https_proxy:-}

packageExtensions:
  'stylelint-config-recommended-scss@*':
    dependencies:
      'postcss': '*'

  # App extensions
  '@carbon/type@*':
    peerDependencies:
      '@carbon/layout': '*'
  '@nabla/vite-plugin-eslint@*':
    dependencies:
      'debug': '*'

  # Server extensions
  '@cspotcode/source-map-support@*':
    dependencies:
      'source-map-support': '*'

  # Storybook extensions
  '@devtools-ds/themes@*':
    peerDependencies:
      'react-dom': '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/instrumenter@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/builder-vite@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      'typescript': '*'
  '@devtools-ds/tree@*':
    peerDependencies:
      'react-dom': '*'
  '@devtools-ds/object-inspector@*':
    peerDependencies:
      'react-dom': '*'
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': '*'