plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: pnpm

httpProxy: ${http_proxy:-}
httpsProxy: ${https_proxy:-}

packageExtensions:
  '@mdx-js/loader@*':
    peerDependencies:
      'react': '*'
  '@storybook/instrumenter@*':
    peerDependencies:
      'core-js': '*'
      'react': '*'
      'react-dom': '*'
  '@storybook/addon-interactions@*':
    peerDependencies:
      'core-js': '*'
  '@storybook/builder-vite@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      'typescript': '*'
  'stylelint-config-recommended-scss@*':
    peerDependencies:
      'postcss': '*'
  'stylelint-config-standard-scss@*':
    peerDependencies:
      'postcss': '*'