plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: ${LINKER:-pnp}

httpProxy: ${http_proxy:-}
httpsProxy: ${https_proxy:-}

packageExtensions:
  'stylelint-config-recommended-scss@*':
    dependencies:
      'postcss': '*'

  # Storybook extensions
  '@storybook/addon-interactions@*':
    peerDependencies:
      'core-js': '*'
  '@storybook/instrumenter@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      'core-js': '*'
  '@storybook/builder-vite@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      'typescript': '*'
  '@mdx-js/loader@*':
    peerDependencies:
      'react': '*'

  # App extensions
  '@carbon/type@*':
    peerDependencies:
      '@carbon/layout': '*'
  '@nabla/vite-plugin-eslint@*':
    dependencies:
      'debug': '*'

  # Server extensions
  '@cspotcode/source-map-support@*':
    dependencies:
      'source-map-support': '*'
