plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: pnp

httpProxy: ${http_proxy:-}
httpsProxy: ${https_proxy:-}

packageExtensions:
  '@carbon/react@*':
    dependencies:
      'prop-types': '*'
  '@nabla/vite-plugin-eslint@*':
    dependencies:
      debug: '*'
  '@carbon/type@*':
    peerDependencies:
      '@carbon/layout': '*'
  'stylelint-config-recommended-scss@*':
    dependencies:
      'postcss': '*'
  'storybook-builder-vite@*':
    peerDependencies:
      'typescript': '*'
      'react': '*'
      'react-dom': '*'
  '@mdx-js/loader@*':
    peerDependencies:
      'react': '*'
  '@storybook/instrumenter@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/testing-library@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  'vitest@*':
    dependencies:
      'jsdom': '*'
  '@cspotcode/source-map-support@*':
    dependencies:
      'source-map-support': '*'
  '@exceptionless/react@*':
    peerDependencies:
      'react': '*'
