plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: pnp

packageExtensions:
  '@nabla/vite-plugin-eslint@*':
    dependencies:
      debug: '*'
  '@carbon/react@*':
    dependencies:
      prop-types: '*'
  '@carbon/type@*':
    peerDependencies:
      '@carbon/layout': '*'
  'stylelint-config-recommended-scss@*':
    dependencies:
      'postcss': '*'
