checksumBehavior: update

enableStrictSsl: false

httpProxy: "http://proxyto02.aizoon.it:8080"

httpsProxy: "http://proxyto02.aizoon.it:8080"

nodeLinker: "${LINKER:-pnp}"

npmRegistryServer: "${npm_registry:-https://registry.yarnpkg.com}"

npmScopes:
  aizoon:
    npmRegistryServer: "https://aramis-nexus.aizoon.it/repository/aramis-npm-group/"

packageExtensions:
  "@carbon/charts-react@*":
    peerDependencies:
      d3: "*"
      sass: "*"
  "@carbon/charts@*":
    dependencies:
      "@carbon/colors": "*"
      d3-array: "*"
      d3-axis: "*"
      d3-brush: "*"
      d3-color: "*"
      d3-ease: "*"
      d3-hierarchy: "*"
      d3-interpolate: "*"
      d3-path: "*"
      d3-scale: "*"
      d3-selection: "*"
      d3-shape: "*"
    peerDependencies:
      sass: "*"
  "@carbon/ibm-products@*":
    dependencies:
      classnames: "*"
      prop-types: "*"
    peerDependencies:
      lodash: "*"
      "@ibm/plex" : "*"
  "@carbon/storybook-addon-theme@*":
    peerDependencies:
      prop-types: "*"
      react-dom: "*"
  "@carbon/type@*":
    peerDependencies:
      "@carbon/layout": "*"
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"
  "@cypress/code-coverage@*":
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      babel-loader: "*"
      webpack: "*"
  "@devtools-ds/object-inspector@*":
    peerDependencies:
      react-dom: "*"
  "@devtools-ds/themes@*":
    peerDependencies:
      react-dom: "*"
  "@devtools-ds/tree@*":
    peerDependencies:
      react-dom: "*"
  "@nabla/vite-plugin-eslint@*":
    dependencies:
      debug: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/builder-vite@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      typescript: "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/telemetry@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  eslint-plugin-i18next@*:
    dependencies:
      lodash: "*"
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
