/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Inet } from './inet';
import { Instance } from './instance';
import { Tenant } from './tenant';

/**
 *
 * @export
 * @interface Asset
 */
export interface Asset {
	/**
	 *
	 * @type {Tenant}
	 * @memberof Asset
	 */
	tenant?: Tenant;
	/**
	 *
	 * @type {number}
	 * @memberof Asset
	 */
	id?: number;
	/**
	 *
	 * @type {Array<Instance>}
	 * @memberof Asset
	 */
	instances?: Array<Instance>;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	hostname?: string;
	/**
	 *
	 * @type {Set<string>}
	 * @memberof Asset
	 */
	paths?: Set<string>;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	ports?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	type?: AssetTypeEnum;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	os?: AssetOsEnum;
	/**
	 *
	 * @type {Inet}
	 * @memberof Asset
	 */
	ip?: Inet;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	dbType?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Asset
	 */
	dbVersion?: string;
}

export const AssetTypeEnum = {
	Os: 'OS',
	Db: 'DB'
} as const;

export type AssetTypeEnum = typeof AssetTypeEnum[keyof typeof AssetTypeEnum];
export const AssetOsEnum = {
	Windows: 'WINDOWS',
	Unix: 'UNIX',
	Mainframe: 'MAINFRAME'
} as const;

export type AssetOsEnum = typeof AssetOsEnum[keyof typeof AssetOsEnum];
