/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvidenceRequestDraftRequestDto } from './evidence-request-draft-request-dto';
import { UserDto } from './user-dto';

/**
 *
 * @export
 * @interface DraftRequestDto
 */
export interface DraftRequestDto {
	/**
	 *
	 * @type {Array<EvidenceRequestDraftRequestDto>}
	 * @memberof DraftRequestDto
	 */
	requests?: Array<EvidenceRequestDraftRequestDto>;
	/**
	 *
	 * @type {string}
	 * @memberof DraftRequestDto
	 */
	suggestedText?: string;
	/**
	 *
	 * @type {Array<UserDto>}
	 * @memberof DraftRequestDto
	 */
	collaborators?: Array<UserDto>;
	/**
	 *
	 * @type {string}
	 * @memberof DraftRequestDto
	 */
	workflowType?: string;
	/**
	 *
	 * @type {string}
	 * @memberof DraftRequestDto
	 */
	type?: DraftRequestDtoTypeEnum;
	/**
	 *
	 * @type {string}
	 * @memberof DraftRequestDto
	 */
	name?: string;
}

export const DraftRequestDtoTypeEnum = {
	Type1: 'TYPE1',
	Type2: 'TYPE2',
	Type3: 'TYPE3'
} as const;

export type DraftRequestDtoTypeEnum =
	typeof DraftRequestDtoTypeEnum[keyof typeof DraftRequestDtoTypeEnum];
