/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IdentityProviderDto
 */
export interface IdentityProviderDto {
	/**
	 *
	 * @type {string}
	 * @memberof IdentityProviderDto
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof IdentityProviderDto
	 */
	alias: string;
	/**
	 *
	 * @type {string}
	 * @memberof IdentityProviderDto
	 */
	url: string;
	/**
	 *
	 * @type {string}
	 * @memberof IdentityProviderDto
	 */
	displayName?: string;
}
