/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tenant } from './tenant';

/**
 *
 * @export
 * @interface Path
 */
export interface Path {
	/**
	 *
	 * @type {Tenant}
	 * @memberof Path
	 */
	tenant?: Tenant;
	/**
	 *
	 * @type {number}
	 * @memberof Path
	 */
	id?: number;
	/**
	 *
	 * @type {string}
	 * @memberof Path
	 */
	route?: string;
}
