/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProcedureAppInstanceKey
 */
export interface ProcedureAppInstanceKey {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureAppInstanceKey
	 */
	procedureId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureAppInstanceKey
	 */
	applicationId?: number;
}
