/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDto } from './user-dto';

/**
 *
 * @export
 * @interface SaveDraftAssociationDto
 */
export interface SaveDraftAssociationDto {
	/**
	 *
	 * @type {UserDto}
	 * @memberof SaveDraftAssociationDto
	 */
	focalPoint?: UserDto;
	/**
	 *
	 * @type {Array<UserDto>}
	 * @memberof SaveDraftAssociationDto
	 */
	delegates?: Array<UserDto>;
	/**
	 *
	 * @type {string}
	 * @memberof SaveDraftAssociationDto
	 */
	controlCode?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SaveDraftAssociationDto
	 */
	frameworkLeafsCodes?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SaveDraftAssociationDto
	 */
	frameworkLeafsNames?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SaveDraftAssociationDto
	 */
	frameworkName?: string;
}
