/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstanceDto } from './instance-dto';
import { MonitoringAssetDto } from './monitoring-asset-dto';

/**
 *
 * @export
 * @interface SaveDraftAssetDto
 */
export interface SaveDraftAssetDto {
	/**
	 *
	 * @type {InstanceDto}
	 * @memberof SaveDraftAssetDto
	 */
	instance?: InstanceDto;
	/**
	 *
	 * @type {Array<MonitoringAssetDto>}
	 * @memberof SaveDraftAssetDto
	 */
	monitoringAssets?: Array<MonitoringAssetDto>;
}
