/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SchedulingDto
 */
export interface SchedulingDto {
	/**
	 * Frequency of the scheduling.
	 * @type {string}
	 * @memberof SchedulingDto
	 */
	frequency: SchedulingDtoFrequencyEnum;
	/**
	 * Starting date of the scheduling.
	 * @type {string}
	 * @memberof SchedulingDto
	 */
	startDate: string;
	/**
	 * Ending date of the scheduling.
	 * @type {string}
	 * @memberof SchedulingDto
	 */
	endDate?: string;
	/**
	 * The days of the week chosen for the scheduling. It\'s empty if the frequency is not weekly.
	 * @type {Array<string>}
	 * @memberof SchedulingDto
	 */
	dayOfWeek?: Array<SchedulingDtoDayOfWeekEnum>;
	/**
	 * The day of the month to run the scheduling.
	 * @type {number}
	 * @memberof SchedulingDto
	 */
	dayOfMonth?: number;
	/**
	 * The number of runs of the scheduling
	 * @type {number}
	 * @memberof SchedulingDto
	 */
	totalRun?: number;
}

export const SchedulingDtoFrequencyEnum = {
	Daily: 'DAILY',
	Weekly: 'WEEKLY',
	Biweekly: 'BIWEEKLY',
	Monthly: 'MONTHLY',
	Quarterly: 'QUARTERLY',
	Semiannual: 'SEMIANNUAL',
	Annual: 'ANNUAL',
	Ondemand: 'ONDEMAND',
	MultipleTimesPerDay: 'MULTIPLE_TIMES_PER_DAY'
} as const;

export type SchedulingDtoFrequencyEnum =
	typeof SchedulingDtoFrequencyEnum[keyof typeof SchedulingDtoFrequencyEnum];
export const SchedulingDtoDayOfWeekEnum = {
	Monday: 'MONDAY',
	Tuesday: 'TUESDAY',
	Wednesday: 'WEDNESDAY',
	Thursday: 'THURSDAY',
	Friday: 'FRIDAY',
	Saturday: 'SATURDAY',
	Sunday: 'SUNDAY'
} as const;

export type SchedulingDtoDayOfWeekEnum =
	typeof SchedulingDtoDayOfWeekEnum[keyof typeof SchedulingDtoDayOfWeekEnum];
