/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDto } from './user-dto';

/**
 *
 * @export
 * @interface StepRequestDto
 */
export interface StepRequestDto {
	/**
	 *
	 * @type {Set<UserDto>}
	 * @memberof StepRequestDto
	 */
	approver?: Set<UserDto>;
	/**
	 *
	 * @type {UserDto}
	 * @memberof StepRequestDto
	 */
	reviewer?: UserDto;
	/**
	 *
	 * @type {string}
	 * @memberof StepRequestDto
	 */
	type?: StepRequestDtoTypeEnum;
	/**
	 *
	 * @type {Set<UserDto>}
	 * @memberof StepRequestDto
	 */
	delegates?: Set<UserDto>;
	/**
	 *
	 * @type {number}
	 * @memberof StepRequestDto
	 */
	id?: number;
}

export const StepRequestDtoTypeEnum = {
	Request: 'REQUEST',
	Approval: 'APPROVAL',
	Upload: 'UPLOAD'
} as const;

export type StepRequestDtoTypeEnum =
	typeof StepRequestDtoTypeEnum[keyof typeof StepRequestDtoTypeEnum];
