/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	RequestArgs,
	BaseAPI,
	RequiredError
} from '../base';
// @ts-ignore
import { AccessLoginDto } from '../models';
// @ts-ignore
import { ApiErrorResponse } from '../models';
// @ts-ignore
import { RefreshTokenDto } from '../models';
/**
 * AccessControllerApi - axios parameter creator
 * @export
 */
export const AccessControllerApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {string} user
		 * @param {string} password
		 * @param {string} tenant
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		login: async (
			user: string,
			password: string,
			tenant: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'user' is not null or undefined
			assertParamExists('login', 'user', user);
			// verify required parameter 'password' is not null or undefined
			assertParamExists('login', 'password', password);
			// verify required parameter 'tenant' is not null or undefined
			assertParamExists('login', 'tenant', tenant);
			const localVarPath = `/api/public/login`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;
			const localVarFormParams = new ((configuration && configuration.formDataCtor) ||
				FormData)();

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (acceptLanguage !== undefined && acceptLanguage !== null) {
				localVarHeaderParameter['Accept-Language'] = String(acceptLanguage);
			}

			if (user !== undefined) {
				localVarFormParams.append('user', user as any);
			}

			if (password !== undefined) {
				localVarFormParams.append('password', password as any);
			}

			if (tenant !== undefined) {
				localVarFormParams.append('tenant', tenant as any);
			}

			localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = localVarFormParams;

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} refreshToken
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		refreshToken: async (
			refreshToken: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'refreshToken' is not null or undefined
			assertParamExists('refreshToken', 'refreshToken', refreshToken);
			const localVarPath = `/api/public/refresh-token`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;
			const localVarFormParams = new ((configuration && configuration.formDataCtor) ||
				FormData)();

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (acceptLanguage !== undefined && acceptLanguage !== null) {
				localVarHeaderParameter['Accept-Language'] = String(acceptLanguage);
			}

			if (refreshToken !== undefined) {
				localVarFormParams.append('refresh-token', refreshToken as any);
			}

			localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = localVarFormParams;

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		}
	};
};

/**
 * AccessControllerApi - functional programming interface
 * @export
 */
export const AccessControllerApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator = AccessControllerApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {string} user
		 * @param {string} password
		 * @param {string} tenant
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async login(
			user: string,
			password: string,
			tenant: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccessLoginDto>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.login(
				user,
				password,
				tenant,
				acceptLanguage,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} refreshToken
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async refreshToken(
			refreshToken: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RefreshTokenDto>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken(
				refreshToken,
				acceptLanguage,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		}
	};
};

/**
 * AccessControllerApi - factory interface
 * @export
 */
export const AccessControllerApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = AccessControllerApiFp(configuration);
	return {
		/**
		 *
		 * @param {string} user
		 * @param {string} password
		 * @param {string} tenant
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		login(
			user: string,
			password: string,
			tenant: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options?: any
		): AxiosPromise<AccessLoginDto> {
			return localVarFp
				.login(user, password, tenant, acceptLanguage, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} refreshToken
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		refreshToken(
			refreshToken: string,
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			options?: any
		): AxiosPromise<RefreshTokenDto> {
			return localVarFp
				.refreshToken(refreshToken, acceptLanguage, options)
				.then(request => request(axios, basePath));
		}
	};
};

/**
 * Request parameters for login operation in AccessControllerApi.
 * @export
 * @interface AccessControllerApiLoginRequest
 */
export interface AccessControllerApiLoginRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AccessControllerApiLogin
	 */
	readonly user: string;

	/**
	 *
	 * @type {string}
	 * @memberof AccessControllerApiLogin
	 */
	readonly password: string;

	/**
	 *
	 * @type {string}
	 * @memberof AccessControllerApiLogin
	 */
	readonly tenant: string;

	/**
	 *
	 * @type {'en-US' | 'it-IT' | 'fr-FR'}
	 * @memberof AccessControllerApiLogin
	 */
	readonly acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR';
}

/**
 * Request parameters for refreshToken operation in AccessControllerApi.
 * @export
 * @interface AccessControllerApiRefreshTokenRequest
 */
export interface AccessControllerApiRefreshTokenRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AccessControllerApiRefreshToken
	 */
	readonly refreshToken: string;

	/**
	 *
	 * @type {'en-US' | 'it-IT' | 'fr-FR'}
	 * @memberof AccessControllerApiRefreshToken
	 */
	readonly acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR';
}

/**
 * AccessControllerApi - object-oriented interface
 * @export
 * @class AccessControllerApi
 * @extends {BaseAPI}
 */
export class AccessControllerApi extends BaseAPI {
	/**
	 *
	 * @param {AccessControllerApiLoginRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof AccessControllerApi
	 */
	public login(
		requestParameters: AccessControllerApiLoginRequest,
		options?: AxiosRequestConfig
	) {
		return AccessControllerApiFp(this.configuration)
			.login(
				requestParameters.user,
				requestParameters.password,
				requestParameters.tenant,
				requestParameters.acceptLanguage,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {AccessControllerApiRefreshTokenRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof AccessControllerApi
	 */
	public refreshToken(
		requestParameters: AccessControllerApiRefreshTokenRequest,
		options?: AxiosRequestConfig
	) {
		return AccessControllerApiFp(this.configuration)
			.refreshToken(
				requestParameters.refreshToken,
				requestParameters.acceptLanguage,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}
}
