/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	RequestArgs,
	BaseAPI,
	RequiredError
} from '../base';
// @ts-ignore
import { ApiErrorResponse } from '../models';
/**
 * FrameworkTreeControllerApi - axios parameter creator
 * @export
 */
export const FrameworkTreeControllerApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {any} [file]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addAssociation: async (
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			file?: any,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/api/framework/uploadcsv/uploadassociation`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;
			const localVarFormParams = new ((configuration && configuration.formDataCtor) ||
				FormData)();

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (acceptLanguage !== undefined && acceptLanguage !== null) {
				localVarHeaderParameter['Accept-Language'] = String(acceptLanguage);
			}

			if (file !== undefined) {
				localVarFormParams.append('file', file as any);
			}

			localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = localVarFormParams;

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		}
	};
};

/**
 * FrameworkTreeControllerApi - functional programming interface
 * @export
 */
export const FrameworkTreeControllerApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator =
		FrameworkTreeControllerApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {any} [file]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async addAssociation(
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			file?: any,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.addAssociation(
				acceptLanguage,
				file,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		}
	};
};

/**
 * FrameworkTreeControllerApi - factory interface
 * @export
 */
export const FrameworkTreeControllerApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = FrameworkTreeControllerApiFp(configuration);
	return {
		/**
		 *
		 * @param {'en-US' | 'it-IT' | 'fr-FR'} [acceptLanguage]
		 * @param {any} [file]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addAssociation(
			acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR',
			file?: any,
			options?: any
		): AxiosPromise<object> {
			return localVarFp
				.addAssociation(acceptLanguage, file, options)
				.then(request => request(axios, basePath));
		}
	};
};

/**
 * Request parameters for addAssociation operation in FrameworkTreeControllerApi.
 * @export
 * @interface FrameworkTreeControllerApiAddAssociationRequest
 */
export interface FrameworkTreeControllerApiAddAssociationRequest {
	/**
	 *
	 * @type {'en-US' | 'it-IT' | 'fr-FR'}
	 * @memberof FrameworkTreeControllerApiAddAssociation
	 */
	readonly acceptLanguage?: 'en-US' | 'it-IT' | 'fr-FR';

	/**
	 *
	 * @type {any}
	 * @memberof FrameworkTreeControllerApiAddAssociation
	 */
	readonly file?: any;
}

/**
 * FrameworkTreeControllerApi - object-oriented interface
 * @export
 * @class FrameworkTreeControllerApi
 * @extends {BaseAPI}
 */
export class FrameworkTreeControllerApi extends BaseAPI {
	/**
	 *
	 * @param {FrameworkTreeControllerApiAddAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof FrameworkTreeControllerApi
	 */
	public addAssociation(
		requestParameters: FrameworkTreeControllerApiAddAssociationRequest = {},
		options?: AxiosRequestConfig
	) {
		return FrameworkTreeControllerApiFp(this.configuration)
			.addAssociation(requestParameters.acceptLanguage, requestParameters.file, options)
			.then(request => request(this.axios, this.basePath));
	}
}
