/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	RequestArgs,
	BaseAPI,
	RequiredError
} from '../base';
// @ts-ignore
import { ApiErrorResponse } from '../models';
// @ts-ignore
import { Procedure } from '../models';
// @ts-ignore
import { ProcedureAppInstance } from '../models';
// @ts-ignore
import { ProcedureAppInstanceKey } from '../models';
/**
 * ProcedureControllerApi - axios parameter creator
 * @export
 */
export const ProcedureControllerApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addApplicationToProcedure: async (
			procedureId: number,
			applicationId: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedureId' is not null or undefined
			assertParamExists('addApplicationToProcedure', 'procedureId', procedureId);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists('addApplicationToProcedure', 'applicationId', applicationId);
			const localVarPath = `/api/procedure/{procedureId}/applications}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (procedureId !== undefined) {
				localVarQueryParameter['procedureId'] = procedureId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteProcedure: async (
			id: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('deleteProcedure', 'id', id);
			const localVarPath = `/api/procedure/{id}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteProcedureApplicationAssociation: async (
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedureId' is not null or undefined
			assertParamExists(
				'deleteProcedureApplicationAssociation',
				'procedureId',
				procedureId
			);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists(
				'deleteProcedureApplicationAssociation',
				'applicationId',
				applicationId
			);
			// verify required parameter 'procedureAppInstanceKey' is not null or undefined
			assertParamExists(
				'deleteProcedureApplicationAssociation',
				'procedureAppInstanceKey',
				procedureAppInstanceKey
			);
			const localVarPath = `/api/procedure/{procedureid}/applications/{applicationid}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (procedureId !== undefined) {
				localVarQueryParameter['procedureId'] = procedureId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				procedureAppInstanceKey,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllApplicationForProcedure: async (
			procedureId: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedureId' is not null or undefined
			assertParamExists('getAllApplicationForProcedure', 'procedureId', procedureId);
			const localVarPath = `/api/procedure/{procedureId}/applications`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (procedureId !== undefined) {
				localVarQueryParameter['procedureId'] = procedureId;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllProcedure: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
			const localVarPath = `/api/procedure`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSingleProcedure: async (
			id: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('getSingleProcedure', 'id', id);
			const localVarPath = `/api/procedure/{id}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSpecificProcedureAppInstance: async (
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedureId' is not null or undefined
			assertParamExists('getSpecificProcedureAppInstance', 'procedureId', procedureId);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists(
				'getSpecificProcedureAppInstance',
				'applicationId',
				applicationId
			);
			// verify required parameter 'procedureAppInstanceKey' is not null or undefined
			assertParamExists(
				'getSpecificProcedureAppInstance',
				'procedureAppInstanceKey',
				procedureAppInstanceKey
			);
			const localVarPath = `/api/procedure/{procedureId}/applications/{applicationId}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (procedureId !== undefined) {
				localVarQueryParameter['procedureId'] = procedureId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			if (procedureAppInstanceKey !== undefined) {
				localVarQueryParameter['procedureAppInstanceKey'] = procedureAppInstanceKey;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstance} procedureAppInstance
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyApplicationToProcedure: async (
			procedureId: number,
			applicationId: number,
			procedureAppInstance: ProcedureAppInstance,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedureId' is not null or undefined
			assertParamExists('modifyApplicationToProcedure', 'procedureId', procedureId);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists('modifyApplicationToProcedure', 'applicationId', applicationId);
			// verify required parameter 'procedureAppInstance' is not null or undefined
			assertParamExists(
				'modifyApplicationToProcedure',
				'procedureAppInstance',
				procedureAppInstance
			);
			const localVarPath = `/api/procedure/{procedureid}/applications/{applicationid}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (procedureId !== undefined) {
				localVarQueryParameter['procedureId'] = procedureId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				procedureAppInstance,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} id
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyProcedure: async (
			id: number,
			procedure: Procedure,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('modifyProcedure', 'id', id);
			// verify required parameter 'procedure' is not null or undefined
			assertParamExists('modifyProcedure', 'procedure', procedure);
			const localVarPath = `/api/procedure/{id}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				procedure,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		newProcedure: async (
			procedure: Procedure,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'procedure' is not null or undefined
			assertParamExists('newProcedure', 'procedure', procedure);
			const localVarPath = `/api/procedure`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				procedure,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		}
	};
};

/**
 * ProcedureControllerApi - functional programming interface
 * @export
 */
export const ProcedureControllerApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator =
		ProcedureControllerApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async addApplicationToProcedure(
			procedureId: number,
			applicationId: number,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcedureAppInstance>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.addApplicationToProcedure(
				procedureId,
				applicationId,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteProcedure(
			id: number,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProcedure(
				id,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteProcedureApplicationAssociation(
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.deleteProcedureApplicationAssociation(
					procedureId,
					applicationId,
					procedureAppInstanceKey,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getAllApplicationForProcedure(
			procedureId: number,
			options?: AxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<Array<ProcedureAppInstance>>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.getAllApplicationForProcedure(
					procedureId,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getAllProcedure(
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Procedure>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProcedure(options);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getSingleProcedure(
			id: number,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Procedure>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleProcedure(
				id,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getSpecificProcedureAppInstance(
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcedureAppInstance>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.getSpecificProcedureAppInstance(
					procedureId,
					applicationId,
					procedureAppInstanceKey,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstance} procedureAppInstance
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async modifyApplicationToProcedure(
			procedureId: number,
			applicationId: number,
			procedureAppInstance: ProcedureAppInstance,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcedureAppInstance>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.modifyApplicationToProcedure(
					procedureId,
					applicationId,
					procedureAppInstance,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} id
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async modifyProcedure(
			id: number,
			procedure: Procedure,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Procedure>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.modifyProcedure(
				id,
				procedure,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async newProcedure(
			procedure: Procedure,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Procedure>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.newProcedure(
				procedure,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		}
	};
};

/**
 * ProcedureControllerApi - factory interface
 * @export
 */
export const ProcedureControllerApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = ProcedureControllerApiFp(configuration);
	return {
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addApplicationToProcedure(
			procedureId: number,
			applicationId: number,
			options?: any
		): AxiosPromise<ProcedureAppInstance> {
			return localVarFp
				.addApplicationToProcedure(procedureId, applicationId, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteProcedure(id: number, options?: any): AxiosPromise<string> {
			return localVarFp
				.deleteProcedure(id, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteProcedureApplicationAssociation(
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options?: any
		): AxiosPromise<string> {
			return localVarFp
				.deleteProcedureApplicationAssociation(
					procedureId,
					applicationId,
					procedureAppInstanceKey,
					options
				)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllApplicationForProcedure(
			procedureId: number,
			options?: any
		): AxiosPromise<Array<ProcedureAppInstance>> {
			return localVarFp
				.getAllApplicationForProcedure(procedureId, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllProcedure(options?: any): AxiosPromise<Array<Procedure>> {
			return localVarFp
				.getAllProcedure(options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSingleProcedure(id: number, options?: any): AxiosPromise<Procedure> {
			return localVarFp
				.getSingleProcedure(id, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstanceKey} procedureAppInstanceKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSpecificProcedureAppInstance(
			procedureId: number,
			applicationId: number,
			procedureAppInstanceKey: ProcedureAppInstanceKey,
			options?: any
		): AxiosPromise<ProcedureAppInstance> {
			return localVarFp
				.getSpecificProcedureAppInstance(
					procedureId,
					applicationId,
					procedureAppInstanceKey,
					options
				)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} procedureId
		 * @param {number} applicationId
		 * @param {ProcedureAppInstance} procedureAppInstance
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyApplicationToProcedure(
			procedureId: number,
			applicationId: number,
			procedureAppInstance: ProcedureAppInstance,
			options?: any
		): AxiosPromise<ProcedureAppInstance> {
			return localVarFp
				.modifyApplicationToProcedure(
					procedureId,
					applicationId,
					procedureAppInstance,
					options
				)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} id
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyProcedure(
			id: number,
			procedure: Procedure,
			options?: any
		): AxiosPromise<Procedure> {
			return localVarFp
				.modifyProcedure(id, procedure, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {Procedure} procedure
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		newProcedure(procedure: Procedure, options?: any): AxiosPromise<Procedure> {
			return localVarFp
				.newProcedure(procedure, options)
				.then(request => request(axios, basePath));
		}
	};
};

/**
 * Request parameters for addApplicationToProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiAddApplicationToProcedureRequest
 */
export interface ProcedureControllerApiAddApplicationToProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiAddApplicationToProcedure
	 */
	readonly procedureId: number;

	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiAddApplicationToProcedure
	 */
	readonly applicationId: number;
}

/**
 * Request parameters for deleteProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiDeleteProcedureRequest
 */
export interface ProcedureControllerApiDeleteProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiDeleteProcedure
	 */
	readonly id: number;
}

/**
 * Request parameters for deleteProcedureApplicationAssociation operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiDeleteProcedureApplicationAssociationRequest
 */
export interface ProcedureControllerApiDeleteProcedureApplicationAssociationRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiDeleteProcedureApplicationAssociation
	 */
	readonly procedureId: number;

	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiDeleteProcedureApplicationAssociation
	 */
	readonly applicationId: number;

	/**
	 *
	 * @type {ProcedureAppInstanceKey}
	 * @memberof ProcedureControllerApiDeleteProcedureApplicationAssociation
	 */
	readonly procedureAppInstanceKey: ProcedureAppInstanceKey;
}

/**
 * Request parameters for getAllApplicationForProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiGetAllApplicationForProcedureRequest
 */
export interface ProcedureControllerApiGetAllApplicationForProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiGetAllApplicationForProcedure
	 */
	readonly procedureId: number;
}

/**
 * Request parameters for getSingleProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiGetSingleProcedureRequest
 */
export interface ProcedureControllerApiGetSingleProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiGetSingleProcedure
	 */
	readonly id: number;
}

/**
 * Request parameters for getSpecificProcedureAppInstance operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiGetSpecificProcedureAppInstanceRequest
 */
export interface ProcedureControllerApiGetSpecificProcedureAppInstanceRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiGetSpecificProcedureAppInstance
	 */
	readonly procedureId: number;

	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiGetSpecificProcedureAppInstance
	 */
	readonly applicationId: number;

	/**
	 *
	 * @type {ProcedureAppInstanceKey}
	 * @memberof ProcedureControllerApiGetSpecificProcedureAppInstance
	 */
	readonly procedureAppInstanceKey: ProcedureAppInstanceKey;
}

/**
 * Request parameters for modifyApplicationToProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiModifyApplicationToProcedureRequest
 */
export interface ProcedureControllerApiModifyApplicationToProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiModifyApplicationToProcedure
	 */
	readonly procedureId: number;

	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiModifyApplicationToProcedure
	 */
	readonly applicationId: number;

	/**
	 *
	 * @type {ProcedureAppInstance}
	 * @memberof ProcedureControllerApiModifyApplicationToProcedure
	 */
	readonly procedureAppInstance: ProcedureAppInstance;
}

/**
 * Request parameters for modifyProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiModifyProcedureRequest
 */
export interface ProcedureControllerApiModifyProcedureRequest {
	/**
	 *
	 * @type {number}
	 * @memberof ProcedureControllerApiModifyProcedure
	 */
	readonly id: number;

	/**
	 *
	 * @type {Procedure}
	 * @memberof ProcedureControllerApiModifyProcedure
	 */
	readonly procedure: Procedure;
}

/**
 * Request parameters for newProcedure operation in ProcedureControllerApi.
 * @export
 * @interface ProcedureControllerApiNewProcedureRequest
 */
export interface ProcedureControllerApiNewProcedureRequest {
	/**
	 *
	 * @type {Procedure}
	 * @memberof ProcedureControllerApiNewProcedure
	 */
	readonly procedure: Procedure;
}

/**
 * ProcedureControllerApi - object-oriented interface
 * @export
 * @class ProcedureControllerApi
 * @extends {BaseAPI}
 */
export class ProcedureControllerApi extends BaseAPI {
	/**
	 *
	 * @param {ProcedureControllerApiAddApplicationToProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public addApplicationToProcedure(
		requestParameters: ProcedureControllerApiAddApplicationToProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.addApplicationToProcedure(
				requestParameters.procedureId,
				requestParameters.applicationId,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiDeleteProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public deleteProcedure(
		requestParameters: ProcedureControllerApiDeleteProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.deleteProcedure(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiDeleteProcedureApplicationAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public deleteProcedureApplicationAssociation(
		requestParameters: ProcedureControllerApiDeleteProcedureApplicationAssociationRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.deleteProcedureApplicationAssociation(
				requestParameters.procedureId,
				requestParameters.applicationId,
				requestParameters.procedureAppInstanceKey,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiGetAllApplicationForProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public getAllApplicationForProcedure(
		requestParameters: ProcedureControllerApiGetAllApplicationForProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.getAllApplicationForProcedure(requestParameters.procedureId, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public getAllProcedure(options?: AxiosRequestConfig) {
		return ProcedureControllerApiFp(this.configuration)
			.getAllProcedure(options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiGetSingleProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public getSingleProcedure(
		requestParameters: ProcedureControllerApiGetSingleProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.getSingleProcedure(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiGetSpecificProcedureAppInstanceRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public getSpecificProcedureAppInstance(
		requestParameters: ProcedureControllerApiGetSpecificProcedureAppInstanceRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.getSpecificProcedureAppInstance(
				requestParameters.procedureId,
				requestParameters.applicationId,
				requestParameters.procedureAppInstanceKey,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiModifyApplicationToProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public modifyApplicationToProcedure(
		requestParameters: ProcedureControllerApiModifyApplicationToProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.modifyApplicationToProcedure(
				requestParameters.procedureId,
				requestParameters.applicationId,
				requestParameters.procedureAppInstance,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiModifyProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public modifyProcedure(
		requestParameters: ProcedureControllerApiModifyProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.modifyProcedure(requestParameters.id, requestParameters.procedure, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {ProcedureControllerApiNewProcedureRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ProcedureControllerApi
	 */
	public newProcedure(
		requestParameters: ProcedureControllerApiNewProcedureRequest,
		options?: AxiosRequestConfig
	) {
		return ProcedureControllerApiFp(this.configuration)
			.newProcedure(requestParameters.procedure, options)
			.then(request => request(this.axios, this.basePath));
	}
}
