/* tslint:disable */
/* eslint-disable */
/**
 * COSMO Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	RequestArgs,
	BaseAPI,
	RequiredError
} from '../base';
// @ts-ignore
import { ApiErrorResponse } from '../models';
// @ts-ignore
import { User } from '../models';
// @ts-ignore
import { UserApplication } from '../models';
// @ts-ignore
import { UserApplicationKey } from '../models';
// @ts-ignore
import { UserProfile } from '../models';
// @ts-ignore
import { UserProfileKey } from '../models';
/**
 * UserControllerApi - axios parameter creator
 * @export
 */
export const UserControllerApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addApplicationToUser: async (
			userId: string,
			applicationId: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userId' is not null or undefined
			assertParamExists('addApplicationToUser', 'userId', userId);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists('addApplicationToUser', 'applicationId', applicationId);
			const localVarPath = `/api/users/{userId}/applications`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (userId !== undefined) {
				localVarQueryParameter['userId'] = userId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addProfileToUser: async (
			userId: string,
			profileId: number,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userId' is not null or undefined
			assertParamExists('addProfileToUser', 'userId', userId);
			// verify required parameter 'profileId' is not null or undefined
			assertParamExists('addProfileToUser', 'profileId', profileId);
			const localVarPath = `/api/users/{userId}/profiles/{profileId}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (userId !== undefined) {
				localVarQueryParameter['userId'] = userId;
			}

			if (profileId !== undefined) {
				localVarQueryParameter['profileId'] = profileId;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUser: async (
			id: string,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('deleteUser', 'id', id);
			const localVarPath = `/api/users/{id}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {UserApplicationKey} userApplicationKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUserApplicationAssociation: async (
			userApplicationKey: UserApplicationKey,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userApplicationKey' is not null or undefined
			assertParamExists(
				'deleteUserApplicationAssociation',
				'userApplicationKey',
				userApplicationKey
			);
			const localVarPath = `/api/users/{userid}/applications/{applicationid}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				userApplicationKey,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfileKey} userProfileKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUserProfileAssociation: async (
			userId: string,
			profileId: number,
			userProfileKey: UserProfileKey,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userId' is not null or undefined
			assertParamExists('deleteUserProfileAssociation', 'userId', userId);
			// verify required parameter 'profileId' is not null or undefined
			assertParamExists('deleteUserProfileAssociation', 'profileId', profileId);
			// verify required parameter 'userProfileKey' is not null or undefined
			assertParamExists('deleteUserProfileAssociation', 'userProfileKey', userProfileKey);
			const localVarPath = `/api/users/{userId}/profiles/{profileId}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (userId !== undefined) {
				localVarQueryParameter['userId'] = userId;
			}

			if (profileId !== undefined) {
				localVarQueryParameter['profileId'] = profileId;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				userProfileKey,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllApplicationOfAUser: async (
			id: string,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('getAllApplicationOfAUser', 'id', id);
			const localVarPath = `/api/users/{id}/applications`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllProfileOfAUser: async (
			id: string,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('getAllProfileOfAUser', 'id', id);
			const localVarPath = `/api/users/{id}/profiles`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllUsers: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
			const localVarPath = `/api/users`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getOneUsers: async (
			id: string,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('getOneUsers', 'id', id);
			const localVarPath = `/api/users/{id}`.replace(
				`{${'id'}}`,
				encodeURIComponent(String(id))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {UserApplication} userApplication
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyApplicationToUserAssociation: async (
			userId: string,
			applicationId: number,
			userApplication: UserApplication,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userId' is not null or undefined
			assertParamExists('modifyApplicationToUserAssociation', 'userId', userId);
			// verify required parameter 'applicationId' is not null or undefined
			assertParamExists(
				'modifyApplicationToUserAssociation',
				'applicationId',
				applicationId
			);
			// verify required parameter 'userApplication' is not null or undefined
			assertParamExists(
				'modifyApplicationToUserAssociation',
				'userApplication',
				userApplication
			);
			const localVarPath = `/api/users/{userId}/applications/{applicationId}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (userId !== undefined) {
				localVarQueryParameter['userId'] = userId;
			}

			if (applicationId !== undefined) {
				localVarQueryParameter['applicationId'] = applicationId;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				userApplication,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfile} userProfile
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyUserProfileAssociation: async (
			userId: string,
			profileId: number,
			userProfile: UserProfile,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'userId' is not null or undefined
			assertParamExists('modifyUserProfileAssociation', 'userId', userId);
			// verify required parameter 'profileId' is not null or undefined
			assertParamExists('modifyUserProfileAssociation', 'profileId', profileId);
			// verify required parameter 'userProfile' is not null or undefined
			assertParamExists('modifyUserProfileAssociation', 'userProfile', userProfile);
			const localVarPath = `/api/users/{userId}/profiles/{profileId}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (userId !== undefined) {
				localVarQueryParameter['userId'] = userId;
			}

			if (profileId !== undefined) {
				localVarQueryParameter['profileId'] = profileId;
			}

			if (userProfile !== undefined) {
				localVarQueryParameter['userProfile'] = userProfile;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		newUser: async (
			user: User,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'user' is not null or undefined
			assertParamExists('newUser', 'user', user);
			const localVarPath = `/api/users`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				user,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		},
		/**
		 *
		 * @param {number} id
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		updateUser: async (
			id: number,
			user: User,
			options: AxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('updateUser', 'id', id);
			// verify required parameter 'user' is not null or undefined
			assertParamExists('updateUser', 'user', user);
			const localVarPath = `/api/users/{id}`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearerAuth required
			await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration);

			if (id !== undefined) {
				localVarQueryParameter['id'] = id;
			}

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				user,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions
			};
		}
	};
};

/**
 * UserControllerApi - functional programming interface
 * @export
 */
export const UserControllerApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator = UserControllerApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async addApplicationToUser(
			userId: string,
			applicationId: number,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserApplication>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.addApplicationToUser(
				userId,
				applicationId,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async addProfileToUser(
			userId: string,
			profileId: number,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfile>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.addProfileToUser(
				userId,
				profileId,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteUser(
			id: string,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {UserApplicationKey} userApplicationKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteUserApplicationAssociation(
			userApplicationKey: UserApplicationKey,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.deleteUserApplicationAssociation(
					userApplicationKey,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfileKey} userProfileKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteUserProfileAssociation(
			userId: string,
			profileId: number,
			userProfileKey: UserProfileKey,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.deleteUserProfileAssociation(
					userId,
					profileId,
					userProfileKey,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getAllApplicationOfAUser(
			id: string,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserApplication>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getAllApplicationOfAUser(
				id,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getAllProfileOfAUser(
			id: string,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserProfile>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProfileOfAUser(
				id,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getAllUsers(
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUsers(options);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getOneUsers(
			id: string,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getOneUsers(id, options);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {UserApplication} userApplication
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async modifyApplicationToUserAssociation(
			userId: string,
			applicationId: number,
			userApplication: UserApplication,
			options?: AxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserApplication>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.modifyApplicationToUserAssociation(
					userId,
					applicationId,
					userApplication,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfile} userProfile
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async modifyUserProfileAssociation(
			userId: string,
			profileId: number,
			userProfile: UserProfile,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfile>> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.modifyUserProfileAssociation(
					userId,
					profileId,
					userProfile,
					options
				);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async newUser(
			user: User,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.newUser(user, options);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		},
		/**
		 *
		 * @param {number} id
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async updateUser(
			id: number,
			user: User,
			options?: AxiosRequestConfig
		): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(
				id,
				user,
				options
			);
			return createRequestFunction(
				localVarAxiosArgs,
				globalAxios,
				BASE_PATH,
				configuration
			);
		}
	};
};

/**
 * UserControllerApi - factory interface
 * @export
 */
export const UserControllerApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = UserControllerApiFp(configuration);
	return {
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addApplicationToUser(
			userId: string,
			applicationId: number,
			options?: any
		): AxiosPromise<UserApplication> {
			return localVarFp
				.addApplicationToUser(userId, applicationId, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		addProfileToUser(
			userId: string,
			profileId: number,
			options?: any
		): AxiosPromise<UserProfile> {
			return localVarFp
				.addProfileToUser(userId, profileId, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUser(id: string, options?: any): AxiosPromise<string> {
			return localVarFp.deleteUser(id, options).then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {UserApplicationKey} userApplicationKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUserApplicationAssociation(
			userApplicationKey: UserApplicationKey,
			options?: any
		): AxiosPromise<string> {
			return localVarFp
				.deleteUserApplicationAssociation(userApplicationKey, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfileKey} userProfileKey
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteUserProfileAssociation(
			userId: string,
			profileId: number,
			userProfileKey: UserProfileKey,
			options?: any
		): AxiosPromise<string> {
			return localVarFp
				.deleteUserProfileAssociation(userId, profileId, userProfileKey, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllApplicationOfAUser(
			id: string,
			options?: any
		): AxiosPromise<Array<UserApplication>> {
			return localVarFp
				.getAllApplicationOfAUser(id, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllProfileOfAUser(id: string, options?: any): AxiosPromise<Array<UserProfile>> {
			return localVarFp
				.getAllProfileOfAUser(id, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getAllUsers(options?: any): AxiosPromise<Array<User>> {
			return localVarFp.getAllUsers(options).then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} id
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getOneUsers(id: string, options?: any): AxiosPromise<User> {
			return localVarFp
				.getOneUsers(id, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} applicationId
		 * @param {UserApplication} userApplication
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyApplicationToUserAssociation(
			userId: string,
			applicationId: number,
			userApplication: UserApplication,
			options?: any
		): AxiosPromise<UserApplication> {
			return localVarFp
				.modifyApplicationToUserAssociation(
					userId,
					applicationId,
					userApplication,
					options
				)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} userId
		 * @param {number} profileId
		 * @param {UserProfile} userProfile
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		modifyUserProfileAssociation(
			userId: string,
			profileId: number,
			userProfile: UserProfile,
			options?: any
		): AxiosPromise<UserProfile> {
			return localVarFp
				.modifyUserProfileAssociation(userId, profileId, userProfile, options)
				.then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		newUser(user: User, options?: any): AxiosPromise<User> {
			return localVarFp.newUser(user, options).then(request => request(axios, basePath));
		},
		/**
		 *
		 * @param {number} id
		 * @param {User} user
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		updateUser(id: number, user: User, options?: any): AxiosPromise<User> {
			return localVarFp
				.updateUser(id, user, options)
				.then(request => request(axios, basePath));
		}
	};
};

/**
 * Request parameters for addApplicationToUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiAddApplicationToUserRequest
 */
export interface UserControllerApiAddApplicationToUserRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiAddApplicationToUser
	 */
	readonly userId: string;

	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiAddApplicationToUser
	 */
	readonly applicationId: number;
}

/**
 * Request parameters for addProfileToUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiAddProfileToUserRequest
 */
export interface UserControllerApiAddProfileToUserRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiAddProfileToUser
	 */
	readonly userId: string;

	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiAddProfileToUser
	 */
	readonly profileId: number;
}

/**
 * Request parameters for deleteUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiDeleteUserRequest
 */
export interface UserControllerApiDeleteUserRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiDeleteUser
	 */
	readonly id: string;
}

/**
 * Request parameters for deleteUserApplicationAssociation operation in UserControllerApi.
 * @export
 * @interface UserControllerApiDeleteUserApplicationAssociationRequest
 */
export interface UserControllerApiDeleteUserApplicationAssociationRequest {
	/**
	 *
	 * @type {UserApplicationKey}
	 * @memberof UserControllerApiDeleteUserApplicationAssociation
	 */
	readonly userApplicationKey: UserApplicationKey;
}

/**
 * Request parameters for deleteUserProfileAssociation operation in UserControllerApi.
 * @export
 * @interface UserControllerApiDeleteUserProfileAssociationRequest
 */
export interface UserControllerApiDeleteUserProfileAssociationRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiDeleteUserProfileAssociation
	 */
	readonly userId: string;

	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiDeleteUserProfileAssociation
	 */
	readonly profileId: number;

	/**
	 *
	 * @type {UserProfileKey}
	 * @memberof UserControllerApiDeleteUserProfileAssociation
	 */
	readonly userProfileKey: UserProfileKey;
}

/**
 * Request parameters for getAllApplicationOfAUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiGetAllApplicationOfAUserRequest
 */
export interface UserControllerApiGetAllApplicationOfAUserRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiGetAllApplicationOfAUser
	 */
	readonly id: string;
}

/**
 * Request parameters for getAllProfileOfAUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiGetAllProfileOfAUserRequest
 */
export interface UserControllerApiGetAllProfileOfAUserRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiGetAllProfileOfAUser
	 */
	readonly id: string;
}

/**
 * Request parameters for getOneUsers operation in UserControllerApi.
 * @export
 * @interface UserControllerApiGetOneUsersRequest
 */
export interface UserControllerApiGetOneUsersRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiGetOneUsers
	 */
	readonly id: string;
}

/**
 * Request parameters for modifyApplicationToUserAssociation operation in UserControllerApi.
 * @export
 * @interface UserControllerApiModifyApplicationToUserAssociationRequest
 */
export interface UserControllerApiModifyApplicationToUserAssociationRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiModifyApplicationToUserAssociation
	 */
	readonly userId: string;

	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiModifyApplicationToUserAssociation
	 */
	readonly applicationId: number;

	/**
	 *
	 * @type {UserApplication}
	 * @memberof UserControllerApiModifyApplicationToUserAssociation
	 */
	readonly userApplication: UserApplication;
}

/**
 * Request parameters for modifyUserProfileAssociation operation in UserControllerApi.
 * @export
 * @interface UserControllerApiModifyUserProfileAssociationRequest
 */
export interface UserControllerApiModifyUserProfileAssociationRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UserControllerApiModifyUserProfileAssociation
	 */
	readonly userId: string;

	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiModifyUserProfileAssociation
	 */
	readonly profileId: number;

	/**
	 *
	 * @type {UserProfile}
	 * @memberof UserControllerApiModifyUserProfileAssociation
	 */
	readonly userProfile: UserProfile;
}

/**
 * Request parameters for newUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiNewUserRequest
 */
export interface UserControllerApiNewUserRequest {
	/**
	 *
	 * @type {User}
	 * @memberof UserControllerApiNewUser
	 */
	readonly user: User;
}

/**
 * Request parameters for updateUser operation in UserControllerApi.
 * @export
 * @interface UserControllerApiUpdateUserRequest
 */
export interface UserControllerApiUpdateUserRequest {
	/**
	 *
	 * @type {number}
	 * @memberof UserControllerApiUpdateUser
	 */
	readonly id: number;

	/**
	 *
	 * @type {User}
	 * @memberof UserControllerApiUpdateUser
	 */
	readonly user: User;
}

/**
 * UserControllerApi - object-oriented interface
 * @export
 * @class UserControllerApi
 * @extends {BaseAPI}
 */
export class UserControllerApi extends BaseAPI {
	/**
	 *
	 * @param {UserControllerApiAddApplicationToUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public addApplicationToUser(
		requestParameters: UserControllerApiAddApplicationToUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.addApplicationToUser(
				requestParameters.userId,
				requestParameters.applicationId,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiAddProfileToUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public addProfileToUser(
		requestParameters: UserControllerApiAddProfileToUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.addProfileToUser(requestParameters.userId, requestParameters.profileId, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiDeleteUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public deleteUser(
		requestParameters: UserControllerApiDeleteUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.deleteUser(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiDeleteUserApplicationAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public deleteUserApplicationAssociation(
		requestParameters: UserControllerApiDeleteUserApplicationAssociationRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.deleteUserApplicationAssociation(requestParameters.userApplicationKey, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiDeleteUserProfileAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public deleteUserProfileAssociation(
		requestParameters: UserControllerApiDeleteUserProfileAssociationRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.deleteUserProfileAssociation(
				requestParameters.userId,
				requestParameters.profileId,
				requestParameters.userProfileKey,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiGetAllApplicationOfAUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public getAllApplicationOfAUser(
		requestParameters: UserControllerApiGetAllApplicationOfAUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.getAllApplicationOfAUser(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiGetAllProfileOfAUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public getAllProfileOfAUser(
		requestParameters: UserControllerApiGetAllProfileOfAUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.getAllProfileOfAUser(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public getAllUsers(options?: AxiosRequestConfig) {
		return UserControllerApiFp(this.configuration)
			.getAllUsers(options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiGetOneUsersRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public getOneUsers(
		requestParameters: UserControllerApiGetOneUsersRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.getOneUsers(requestParameters.id, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiModifyApplicationToUserAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public modifyApplicationToUserAssociation(
		requestParameters: UserControllerApiModifyApplicationToUserAssociationRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.modifyApplicationToUserAssociation(
				requestParameters.userId,
				requestParameters.applicationId,
				requestParameters.userApplication,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiModifyUserProfileAssociationRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public modifyUserProfileAssociation(
		requestParameters: UserControllerApiModifyUserProfileAssociationRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.modifyUserProfileAssociation(
				requestParameters.userId,
				requestParameters.profileId,
				requestParameters.userProfile,
				options
			)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiNewUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public newUser(
		requestParameters: UserControllerApiNewUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.newUser(requestParameters.user, options)
			.then(request => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {UserControllerApiUpdateUserRequest} requestParameters Request parameters.
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof UserControllerApi
	 */
	public updateUser(
		requestParameters: UserControllerApiUpdateUserRequest,
		options?: AxiosRequestConfig
	) {
		return UserControllerApiFp(this.configuration)
			.updateUser(requestParameters.id, requestParameters.user, options)
			.then(request => request(this.axios, this.basePath));
	}
}
